"use client";
import './globals.css'

import { CacheProvider } from '@chakra-ui/next-js'
import { ChakraProvider, extendTheme, theme } from "@chakra-ui/react";




export const metadata = {
	title : 'Create Next App', description : 'Generated by create next app',
}

export default function RootLayout( { children } ) {

	const colors = {
		brand: {
			900: '#1a365d',
			800: '#153e75',
			700: '#2a69ac',
		},
	}

	const theme = extendTheme({ colors })

	return (

		<html lang="en">
		<body>
		<CacheProvider>
			<ChakraProvider theme={theme}>
				{ children }
			</ChakraProvider>
		</CacheProvider>
		</body>
		</html>

	);
}
